### ISSUE TITLE
As a User, I want a Manual Refresh on the widget

### ISSUE THREAD

**Issue by GurkomalSRao** [Nick9500/ministocks#11]
As a user, I want to be able to manually refresh information
[**SP**: 1]
[**Priority**: 2]
[**Risk**: low]

**_Demo_**
**Scenario 1**: User presses "Refresh"  button

**_Task Estimation (Hours)_**
**Task 1**: Research how to implement manual refresh on widget (.5h)
**Task 2**: Discuss with assignee's (.5h) 
~~**Task 3**: Implement pull down refresh feature (.5h)~~
**Task 4**: Implement button refresh feature (.5h)
**Task 4**: Validate potential flaws i.e infinite refresh (.5h)
**Task 5**: Modify and review with assignee's (1.5h)

**_Testing Template_**

Test # | Input | Expected Output | Status
-- | -- | -- | --
1 | None | None  | Pass/Fail
2  | None  | None  | Pass/Fail
3 | None  |None  | Pass/Fail

**Comment by GurkomalSRao** [comment]
Sample of Demo
![390feature1](https://user-images.githubusercontent.com/6819864/35549565-2728b698-0554-11e8-8b8f-eb80517f1e01.png)

**Comment by Nick9500** [comment]
![controls](https://user-images.githubusercontent.com/4484946/36403433-dc132020-15b2-11e8-8242-b64ddd7b05dd.jpeg)

**Comment by Nick9500** [comment]
Test Writing In Progress

**Comment by Nick9500** [comment]
**Manual Testing** because no new methods were implemented. New layout elements were added (2 buttons), and callbacks were re-routed from leftTouch, rightTouch to PREFERENCES, REFRESH buttons accordingly. Manual tests can be found below: 
-Delete widget, quickly readd it, readd stocks to track, then refresh after a few seconds
-Repeatedly pressing REFRESH
**Caution**: Ensure that markets are open when testing. NYSE, FX, NASDAQ all open and close at different times.

**Comment by Nick9500** [comment]
To Demo:
-Long Press Homescreen
-Add instance of ministocks widget
-Add stocks to track via Preferences -> Stocks Setup
-Wait a few minutes (Ensure stock market is open)
-Tap the refresh button the lower left
